"""
Disease Knowledge Base and Agronomic Encyclopedia
Contains scientific details, pathogen info, symptoms, severity metrics,
organic remedies, chemical fungicides, and preventive advice for all 15 classes across 5 crops.
"""

DISEASE_KNOWLEDGE = {
    "Potato": {
        "Healthy": {
            "scientific_name": "Solanum tuberosum (Healthy Leaf)",
            "pathogen_type": "None (Optimum Plant Health)",
            "causal_agent": "N/A",
            "severity_level": "Healthy",
            "severity_code": "LOW",
            "severity_color": "#10B981",
            "visual_symptoms": [
                "Lush green, uniform foliar pigmentation without lesions or chlorosis.",
                "Smooth leaf margin and intact vascular turgidity.",
                "Absence of necrotic spotting, curling, or fungal sporulation.",
            ],
            "organic_management": [
                "Maintain optimal soil microbiome balance using well-rotted farmyard compost.",
                "Prophylactic foliar spray of Trichoderma harzianum or Bacillus subtilis every 14 days.",
                "Apply cold-pressed neem seed oil (3-5 ml/L) as a deterrent for potential insect vectors.",
            ],
            "chemical_management": [
                "No chemical fungicides needed.",
                "Apply balanced N-P-K foliar micronutrient spray (19:19:19 @ 3 g/L) to sustain vegetative vigor.",
            ],
            "prevention_guidelines": [
                "Practice 3-year crop rotation with non-solanaceous crops (e.g., legumes or cereals).",
                "Ensure proper row spacing (60 cm x 20 cm) for adequate air circulation.",
                "Use certified disease-free seed tubers.",
            ],
        },
        "Early_Blight": {
            "scientific_name": "Alternaria solani",
            "pathogen_type": "Fungal Ascomycete",
            "causal_agent": "Alternaria solani Sorauer",
            "severity_level": "Moderate",
            "severity_code": "MEDIUM",
            "severity_color": "#F59E0B",
            "visual_symptoms": [
                "Concentric dark brown to black rings creating characteristic 'bullseye' target-board lesions.",
                "Lesions primarily initiate on older, lower canopy foliage.",
                "Surrounding leaf tissue turns chlorotic (yellow halo) as the lesion expands.",
                "Severe infection leads to complete senescence and defoliation.",
            ],
            "organic_management": [
                "Prune and safely burn or bury heavily infected bottom leaves immediately.",
                "Apply bio-fungicide Bacillus amyloliquefaciens or Trichoderma viride (5 g/L).",
                "Foliar spray with Copper octanoate (copper soap) or Bordeaux mixture (1%) at 7-day intervals.",
            ],
            "chemical_management": [
                "Mancozeb 75% WP (Dithane M-45) @ 2.5 g/L water (protective contact).",
                "Azoxystrobin 23% SC @ 1 ml/L or Difenoconazole 25% EC (Score) @ 0.5 ml/L (systemic).",
                "Alternate between contact and systemic fungicides to prevent pathogen resistance.",
            ],
            "prevention_guidelines": [
                "Employ drip irrigation to prevent foliar wetting; avoid overhead sprinklers.",
                "Maintain adequate potassium and nitrogen levels (stress increases susceptibility).",
                "Mulch beds with clean straw to minimize soil-splash inoculation during rain.",
            ],
        },
        "Late_Blight": {
            "scientific_name": "Phytophthora infestans",
            "pathogen_type": "Oomycete (Water Mold)",
            "causal_agent": "Phytophthora infestans (Mont.) de Bary",
            "severity_level": "Critical / Severe",
            "severity_code": "CRITICAL",
            "severity_color": "#EF4444",
            "visual_symptoms": [
                "Irregular water-soaked, greasy, pale to dark lesions starting at leaf tips and margins.",
                "Rapid expansion into large dark brown/purplish necrotic blights.",
                "Delicate white fuzzy fungal-like downy growth visible on leaf undersides under humid conditions.",
                "Rapid collapse of foliage and foul rotten smell in advanced field infection.",
            ],
            "organic_management": [
                "Strict rogueing: immediately uproot and incinerate infected plants to arrest spore dispersion.",
                "Prophylactic Bordeaux mixture (1:1:100) or Copper hydroxide (2 g/L) before rainy spells.",
                "Biocontrol with Pseudomonas fluorescens (10 ml/L) as a preventive shield.",
            ],
            "chemical_management": [
                "Curative Systemic: Cymoxanil 8% + Mancozeb 64% WP (Curzate) @ 2.5 g/L.",
                "Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold) @ 2.0 g/L.",
                "Dimethomorph 50% WP (Acrobat) @ 1.0 g/L alternated with Chlorothalonil 75% WP @ 2 g/L.",
            ],
            "prevention_guidelines": [
                "Monitor relative humidity (>90%) and temperature (15-22 C) which trigger blight outbreaks.",
                "Ensure high-ridge earthing-up to prevent spores washing down into tubers.",
                "Destroy cull piles and self-sown volunteer potato vines before planting season.",
            ],
        },
    },
    "Tomato": {
        "Healthy": {
            "scientific_name": "Solanum lycopersicum (Healthy Leaf)",
            "pathogen_type": "None (Optimum Foliar Health)",
            "causal_agent": "N/A",
            "severity_level": "Healthy",
            "severity_code": "LOW",
            "severity_color": "#10B981",
            "visual_symptoms": [
                "Deep green, vibrant compound leaves with healthy glandular trichomes.",
                "Uniform foliage distribution with active apical shoot growth.",
                "No curling, necrotic spots, chlorotic veining, or water soaking.",
            ],
            "organic_management": [
                "Maintain balanced soil fertility using vermicompost and seaweed extract spray.",
                "Preventive spraying with Trichoderma harzianum @ 4 g/L every 10-15 days.",
                "Apply potassium silicate (2 ml/L) to strengthen plant cell wall cuticles.",
            ],
            "chemical_management": [
                "No therapeutic chemical intervention needed.",
                "Calcium chloride or calcium nitrate (1.5 g/L) foliar spray to prevent blossom end rot.",
            ],
            "prevention_guidelines": [
                "Stake plants securely to keep lower leaves elevated at least 25-30 cm above soil level.",
                "Prune indeterminate sucker shoots with sanitized shears.",
                "Maintain consistent root-zone moisture through drip irrigation.",
            ],
        },
        "Early_Blight": {
            "scientific_name": "Alternaria linariae / Alternaria solani",
            "pathogen_type": "Fungal Ascomycete",
            "causal_agent": "Alternaria linariae (formerly A. solani)",
            "severity_level": "Moderate",
            "severity_code": "MEDIUM",
            "severity_color": "#F59E0B",
            "visual_symptoms": [
                "Brown-to-black spots with pronounced concentric rings (target spot appearance).",
                "Progresses from oldest lower foliage upwards.",
                "Extensive chlorosis around lesions causing premature leaf drop and fruit sunscald.",
                "Collar rot lesions may also form at the stem base of young seedlings.",
            ],
            "organic_management": [
                "Strip off all infected lower leaves up to the first fruit cluster and destroy safely.",
                "Foliar spray with Copper Oxychloride (COC) 50% WP @ 2.5 g/L.",
                "Neem oil (5 ml/L) combined with potassium bicarbonate (3 g/L) as a foliar wash.",
            ],
            "chemical_management": [
                "Chlorothalonil 75% WP (Kavach / Bravo) @ 2.0 g/L (broad-spectrum protectant).",
                "Tebuconazole 25.9% EC (Folicur) @ 1 ml/L or Azoxystrobin + Difenoconazole (Amistar Top) @ 1 ml/L.",
                "Spray during early morning or late afternoon; repeat in 7-10 days if humid weather persists.",
            ],
            "prevention_guidelines": [
                "Maintain wide spacing (60-75 cm between rows) for optimal aeration.",
                "Mulch with black polythene or clean organic mulch to prevent rain-splash transmission.",
                "Avoid overhead irrigation; keep foliage dry.",
            ],
        },
        "Late_Blight": {
            "scientific_name": "Phytophthora infestans",
            "pathogen_type": "Oomycete Pathogen",
            "causal_agent": "Phytophthora infestans",
            "severity_level": "Critical / Severe",
            "severity_code": "CRITICAL",
            "severity_color": "#EF4444",
            "visual_symptoms": [
                "Large, dark, water-soaked, irregular olive-green to black greasy lesions on leaves and petioles.",
                "Delicate white fluffy sporulation on undersides of leaves during wet, cool, humid weather.",
                "Stems exhibit dark brown-to-black greasy girdling lesions.",
                "Green and ripe fruits develop firm, sunken, dark brown greasy blotches with rough texture.",
            ],
            "organic_management": [
                "Immediately quarantine and remove all symptomatic plants and infected fruit.",
                "Apply fixed copper fungicides (Copper Hydroxide @ 2 g/L) every 5-7 days under threat conditions.",
                "Bio-protective drench with Bacillus subtilis (Serenade ASO) @ 5 ml/L.",
            ],
            "chemical_management": [
                "Famoxadone 16.6% + Cymoxanil 22.1% SC (Equation Pro) @ 1 ml/L.",
                "Dimethomorph 50% WP @ 1 g/L combined with Mancozeb 75% WP @ 2 g/L.",
                "Mandipropamid 23.4% SC (Revus) @ 0.8 ml/L for robust systemic protection.",
            ],
            "prevention_guidelines": [
                "Plant resistant cultivars (e.g., Defiant Ph-R, Mountain Merit, Iron Lady).",
                "Eradicate nightshade weeds and volunteer tomato/potato plants near fields.",
                "Install rain-shelters or polyhouse structures in high-rainfall zones.",
            ],
        },
    },
    "Apple": {
        "Healthy": {
            "scientific_name": "Malus domestica (Healthy Foliage)",
            "pathogen_type": "None (Optimum Foliar Health)",
            "causal_agent": "N/A",
            "severity_level": "Healthy",
            "severity_code": "LOW",
            "severity_color": "#10B981",
            "visual_symptoms": [
                "Glossy, leathery leaves with crisp serrated margins.",
                "Uniform rich green color across upper and lower laminae.",
                "No velvety lesions, rust pustules, or distortion.",
            ],
            "organic_management": [
                "Apply dormant horticultural oil spray in late winter to suppress overwintering pests.",
                "Prophylactic foliar spray of compost tea or beneficial mycorrhizal wash.",
                "Maintain orchard soil biodiversity with organic cover cropping (white clover).",
            ],
            "chemical_management": [
                "No therapeutic chemical fungicide required.",
                "Apply foliar zinc and boron during pink-bud stage to support blossom set.",
            ],
            "prevention_guidelines": [
                "Perform annual winter dormant canopy pruning to maximize sunlight penetration and air movement.",
                "Ensure proper tree spacing and clean orchard floor sanitation.",
            ],
        },
        "Apple_Scab": {
            "scientific_name": "Venturia inaequalis",
            "pathogen_type": "Ascomycete Fungus",
            "causal_agent": "Venturia inaequalis (Cooke) G. Winter",
            "severity_level": "Severe",
            "severity_code": "HIGH",
            "severity_color": "#DC2626",
            "visual_symptoms": [
                "Dull olive-green, velvety circular spots with indistinct margins on leaf upper surface.",
                "Lesions turn dark brown to black, becoming corky and thickened over time.",
                "Leaves curl, wrinkle, dwarf, and drop prematurely.",
                "Infected fruit shows rough, scabby, cracked, dark lesions that stunt development.",
            ],
            "organic_management": [
                "Shred or rake and compost fallen overwintered leaves to destroy ascospore source.",
                "Liquid Lime Sulfur (2-3%) during dormant bud swell stage.",
                "Potassium bicarbonate (3-5 g/L) or Wettable Sulfur (3 g/L) at tight cluster through petal fall.",
            ],
            "chemical_management": [
                "Myclobutanil 10% WP (Systhane) @ 0.5 g/L (curative systemic).",
                "Difenoconazole 25% EC (Score) @ 0.3 ml/L or Kresoxim-methyl 44.3% SC @ 0.5 ml/L.",
                "Captan 50% WP @ 2.5 g/L or Dodine 65% WP @ 1.0 g/L for contact protection.",
            ],
            "prevention_guidelines": [
                "Utilize scab-resistant apple cultivars (e.g., Prima, Priscilla, Liberty, Honeycrisp).",
                "Spray 5% agricultural urea solution onto orchard floor in autumn to accelerate leaf decay.",
                "Use Mills Scab Period calculators to time protective sprays before wet infection periods.",
            ],
        },
        "Cedar_Apple_Rust": {
            "scientific_name": "Gymnosporangium juniperi-virginianae",
            "pathogen_type": "Heteroecious Rust Fungus",
            "causal_agent": "Gymnosporangium juniperi-virginianae Schwein.",
            "severity_level": "Moderate",
            "severity_code": "MEDIUM",
            "severity_color": "#F59E0B",
            "visual_symptoms": [
                "Brilliant bright yellow-orange to reddish circular spots on upper leaf surfaces.",
                "Tiny black specks (pycnia) appear inside the center of yellow spots.",
                "Raised, tube-like projections (aecia) appear on the leaf underside beneath the spots.",
                "Severe foliar spotting triggers early summer defoliation and fruit blemish.",
            ],
            "organic_management": [
                "Rake and remove infected leaves from around the tree base.",
                "Sulfur or Copper-based fungicides applied preventively from pink bud through petal fall.",
                "Physical removal of eastern red cedar galls within 1 km radius of orchard.",
            ],
            "chemical_management": [
                "Myclobutanil (Rally 40WSP) @ 0.3 g/L.",
                "Mancozeb 75% WP @ 2.5 g/L (protectant applied prior to spring rain events).",
                "Propiconazole 25% EC (Tilt) @ 0.5 ml/L or Trifloxystrobin (Flint 50 WG) @ 0.2 g/L.",
            ],
            "prevention_guidelines": [
                "Eradicate cedar apple galls on nearby Juniper trees in early spring.",
                "Plant rust-resistant cultivars (e.g., Enterprise, Freedom, Liberty, Redfree).",
                "Time fungicide applications to match cedar spore release (bud break to 3 weeks post-petal fall).",
            ],
        },
    },
    "Corn": {
        "Healthy": {
            "scientific_name": "Zea mays (Healthy Leaf)",
            "pathogen_type": "None (Optimum Crop Health)",
            "causal_agent": "N/A",
            "severity_level": "Healthy",
            "severity_code": "LOW",
            "severity_color": "#10B981",
            "visual_symptoms": [
                "Elongated, arching blade with uniform emerald-green color.",
                "Prominent, clear central midrib without discoloration.",
                "Clean leaf margins without stripes, pustules, or necrotic firing.",
            ],
            "organic_management": [
                "Apply mycorrhizal bio-fertilizers (VAM) at sowing to enhance root phosphorus uptake.",
                "Maintain organic soil mulch to preserve soil moisture and stabilize soil temperatures.",
                "Foliar seaweed extract (2 ml/L) during knee-high (V6) vegetative stage.",
            ],
            "chemical_management": [
                "No chemical fungicides necessary.",
                "Ensure balanced nitrogen application (split dosage at sowing and knee-high).",
            ],
            "prevention_guidelines": [
                "Rotate with soybeans, cowpeas, or other legumes to disrupt monoculture pathogen build-up.",
                "Maintain recommended plant population (60,000 - 75,000 plants/ha).",
                "Test soil annually for zinc and boron micronutrient balance.",
            ],
        },
        "Common_Rust": {
            "scientific_name": "Puccinia sorghi",
            "pathogen_type": "Basidiomycete Fungus",
            "causal_agent": "Puccinia sorghi Schwein.",
            "severity_level": "Moderate",
            "severity_code": "MEDIUM",
            "severity_color": "#F59E0B",
            "visual_symptoms": [
                "Small, oval to elongate, cinnamon-brown to reddish powdery pustules (uredinia).",
                "Pustules erupt prominently on BOTH upper and lower leaf surfaces.",
                "Leaves turn chlorotic and brown if pustules coalesce densely.",
                "Rust pustules turn blackish-brown later in the season as teliospores form.",
            ],
            "organic_management": [
                "Apply potassium bicarbonate (5 g/L) or horticultural sulfur dust (2-3 g/L) at early detection.",
                "Foliar application of Bacillus subtilis or neem seed extract (3%).",
                "Prompt destruction of infected stover residues after harvest.",
            ],
            "chemical_management": [
                "Azoxystrobin 18.2% + Difenoconazole 11.4% SC (Amistar Top) @ 1 ml/L.",
                "Pyraclostrobin (Headline) @ 0.8 ml/L or Propiconazole 25% EC (Tilt) @ 1 ml/L.",
                "Mancozeb 75% WP @ 2.5 g/L for contact suppression prior to tasseling.",
            ],
            "prevention_guidelines": [
                "Plant rust-resistant corn hybrid varieties with Rp gene resistance.",
                "Plant early in the season to avoid peak summer windborne urediniospore storms.",
                "Apply fungicide when rust pustules appear on leaves prior to tasseling (VT stage).",
            ],
        },
        "Northern_Leaf_Blight": {
            "scientific_name": "Exserohilum turcicum",
            "pathogen_type": "Fungal Ascomycete",
            "causal_agent": "Exserohilum turcicum (Pass.) K.J. Leonard & Suggs",
            "severity_level": "Severe",
            "severity_code": "HIGH",
            "severity_color": "#DC2626",
            "visual_symptoms": [
                "Large, elongated, cigar-shaped or elliptical grayish-green to tan lesions.",
                "Lesions measure 2.5 to 15 cm long and up to 2 cm wide.",
                "Dark, velvety fungal sporulation visible within lesions during humid weather.",
                "Extensive blighting gives the crop a prematurely frosted or burnt canopy appearance.",
            ],
            "organic_management": [
                "Deep autumn plowing of infected crop residue to bury fungal overwintering conidia.",
                "Foliar bio-protection with Trichoderma viride (5 g/L) at knee-high stage.",
                "Application of copper sulfate pentahydrate bio-chelate.",
            ],
            "chemical_management": [
                "Picoxystrobin 6.78% + Cyproconazole 2.82% SC (Aproach Prima) @ 1 ml/L.",
                "Azoxystrobin + Propiconazole (Quilt Xcel) @ 1.25 ml/L.",
                "Chlorothalonil 75% WP @ 2 g/L applied early at tassel emergence if lesions are present.",
            ],
            "prevention_guidelines": [
                "Select hybrids with single-gene (Ht1, Ht2, Ht3) or high quantitative polygenic resistance.",
                "Practice minimum 1-year crop rotation out of corn in no-till fields.",
                "Scout fields weekly starting at V8 through silking stage.",
            ],
        },
    },
    "Grape": {
        "Healthy": {
            "scientific_name": "Vitis vinifera (Healthy Vine Foliage)",
            "pathogen_type": "None (Optimum Foliar Health)",
            "causal_agent": "N/A",
            "severity_level": "Healthy",
            "severity_code": "LOW",
            "severity_color": "#10B981",
            "visual_symptoms": [
                "Supple, palmately lobed leaves with vibrant emerald green coloring.",
                "Clean prominent venation without chlorosis, necroses, or oil-spots.",
                "Healthy active tendril and shoot elongation with uniform internode spacing.",
            ],
            "organic_management": [
                "Apply sea-kelp extract (2 ml/L) and humic acid to promote root vine vigor.",
                "Prophylactic foliar spray of Ampelomyces quisqualis or Trichoderma harzianum (4 g/L).",
                "Ensure balanced canopy nutrition with micronutrient iron-zinc chelate foliar spray.",
            ],
            "chemical_management": [
                "No chemical fungicide needed.",
                "Dormant lime-sulfur wash during winter pruning to eliminate dormant spore inoculum.",
            ],
            "prevention_guidelines": [
                "Employ shoot positioning, hedging, and leaf stripping around bunch zones for airflow.",
                "Maintain drip irrigation lines; avoid any overhead wetting.",
                "Implement cover crops between vineyard rows to regulate canopy humidity.",
            ],
        },
        "Black_Rot": {
            "scientific_name": "Guignardia bidwellii",
            "pathogen_type": "Ascomycete Fungus",
            "causal_agent": "Guignardia bidwellii (Ellis) Viala & Ravaz",
            "severity_level": "Severe",
            "severity_code": "HIGH",
            "severity_color": "#DC2626",
            "visual_symptoms": [
                "Small, circular to irregular reddish-brown necrotic spots with thin dark brown borders.",
                "Tiny black speck-like fruiting bodies (pycnidia) arranged in a distinctive circle inside the lesion.",
                "Shoots and petioles develop elongated, sunken, purple-to-black cankers.",
                "Infected grapes turn into shriveled, hard, wrinkled black mummies adhering to the cluster.",
            ],
            "organic_management": [
                "Hand-collect and remove all shriveled black berry mummies from vines and soil floor.",
                "Fixed copper fungicides (Copper Hydroxide @ 2 g/L) or Bordeaux mixture (1%) at pre/post-bloom.",
                "Apply wettable sulfur (3 g/L) during early shoot growth (10-25 cm shoot length).",
            ],
            "chemical_management": [
                "Myclobutanil 40% WP (Rally) @ 0.3 g/L or Difenoconazole 25% EC (Score) @ 0.5 ml/L.",
                "Kresoxim-methyl 44.3% SC (Sovran) @ 0.5 ml/L or Azoxystrobin (Abound) @ 1 ml/L.",
                "Mancozeb 75% WP @ 2.5 g/L applied starting at bud-break through 4 weeks post-bloom.",
            ],
            "prevention_guidelines": [
                "Canopy management: prune vines to vertical shoot positioning (VSP) for sunlight exposure.",
                "Destroy all overwintered berry mummies during winter pruning before spring bud-burst.",
                "Maintain strict preventive spray coverage from early bloom until berries reach 6-8 mm diameter.",
            ],
        },
        "Leaf_Blight": {
            "scientific_name": "Pseudocercospora vitis / Isariopsis clavispora",
            "pathogen_type": "Fungal Ascomycete",
            "causal_agent": "Pseudocercospora vitis (Lev.) Speg. (formerly Isariopsis clavispora)",
            "severity_level": "Moderate to High",
            "severity_code": "HIGH",
            "severity_color": "#EA580C",
            "visual_symptoms": [
                "Distinct, irregular, angular brown to dark maroon-brown lesions delimited by leaf veins.",
                "Lesions often coalesce to produce extensive foliar blighting and marginal scorching.",
                "Under high humidity, an olive-brown to dark gray velvety mold layer forms on the underside.",
                "Severe attacks lead to premature leaf chlorosis, extensive defoliation, and delayed berry ripening.",
            ],
            "organic_management": [
                "Prune heavily infected leaves and canes, then burn or compost far from vineyard.",
                "Spray Bordeaux mixture (1%) or Copper Oxychloride 50% WP @ 2.5 g/L immediately post-harvest.",
                "Bio-protection using Bacillus subtilis or Trichoderma viride (4 g/L).",
            ],
            "chemical_management": [
                "Carbendazim 50% WP (Bavistin) @ 1.0 g/L or Thiophanate-methyl 70% WP (Topsin-M) @ 1.0 g/L.",
                "Tebuconazole 25.9% EC (Folicur) @ 0.75 ml/L or Hexaconazole 5% EC (Contaf) @ 1.0 ml/L.",
                "Azoxystrobin 11% + Tebuconazole 18.3% SC (Custodia) @ 1.5 ml/L.",
            ],
            "prevention_guidelines": [
                "Perform summer pruning and de-suckering to ensure proper air circulation through the canopy.",
                "Avoid excessive late-season nitrogen fertilizers which produce succulent foliage.",
                "Apply a clean post-harvest fungicide spray before autumn leaf-fall.",
            ],
        },
    },
}

EMPIRICAL_EVALUATION_METRICS = {
    "Potato": {
        "model_architecture": "Custom Dual-Pool CNN (Conv2D + BatchNorm + Dual Pooling)",
        "parameter_count": "11.1 Million",
        "heldout_accuracy": 98.21,
        "heldout_loss": 0.0812,
        "internal_real_world_accuracy": 96.70,
        "external_field_accuracy": 92.40,
        "classes": ["Healthy", "Early_Blight", "Late_Blight"],
        "dataset_size": "2,400+ balanced images",
        "key_strength": "High robustness to laboratory and soil-background variance.",
    },
    "Tomato": {
        "model_architecture": "MobileNetV2 (Fine-Tuned Transfer Learning, ImageNet weights)",
        "parameter_count": "2.8 Million",
        "heldout_accuracy": 97.78,
        "heldout_loss": 0.0745,
        "internal_real_world_accuracy": 100.0,
        "external_field_accuracy": 60.00,
        "classes": ["Healthy", "Early_Blight", "Late_Blight"],
        "dataset_size": "3,000+ balanced images",
        "key_strength": "Ultra-lightweight footprint (11.6 MB), ideal for edge mobile inference.",
    },
    "Apple": {
        "model_architecture": "MobileNetV2 (Transfer Learning with Top Classification Head)",
        "parameter_count": "2.9 Million",
        "heldout_accuracy": 97.75,
        "heldout_loss": 0.0911,
        "internal_real_world_accuracy": 96.67,
        "external_field_accuracy": 56.67,
        "classes": ["Healthy", "Apple_Scab", "Cedar_Apple_Rust"],
        "dataset_size": "1,800+ balanced images",
        "key_strength": "Excellent sensitivity on complex rust pycnidia and scabby textures.",
    },
    "Corn": {
        "model_architecture": "MobileNetV2 (Fine-Tuned Transfer Learning)",
        "parameter_count": "2.9 Million",
        "heldout_accuracy": 97.41,
        "heldout_loss": 0.0894,
        "internal_real_world_accuracy": 100.0,
        "external_field_accuracy": 83.33,
        "classes": ["Healthy", "Common_Rust", "Northern_Leaf_Blight"],
        "dataset_size": "1,800 balanced images",
        "key_strength": "Outstanding 83.3% zero-shot generalization on real-world Indian maize fields.",
    },
    "Grape": {
        "model_architecture": "MobileNetV2 (Transfer Learning with Dual Dense Head)",
        "parameter_count": "2.9 Million",
        "heldout_accuracy": 95.56,
        "heldout_loss": 0.1656,
        "internal_real_world_accuracy": 96.67,
        "external_field_accuracy": 76.67,
        "classes": ["Healthy", "Black_Rot", "Leaf_Blight"],
        "dataset_size": "1,800 balanced images (PlantVillage + GVLiD Mendeley)",
        "key_strength": "Trained on real Indian vineyard imagery (GVLiD Maharashtra); 100% precision on Black Rot.",
    },
}
